UefiDump: add EBBR profile table dump support
- Add utility to dump EFI Conformance Profiles Table
- Save table contents to file for ACS result collection
- Write error information when table retrieval or file write fails
- Fix bash formatting in build-uefi-apps.sh
- Implemented a logic to dump ebbr_profile_table.log to Current Working Directory as a default directory
  if \\acs_results_template\\acs_results\\uefi_dump directory has not found

Signed-off-by: Sathisha S <sathisha.shivaramappa@arm.com>
Change-Id: Ic23cac6578dc54e8f1035360fd95dcd8eed531de

diff --git a/.github/workflows/daily_build.yaml b/.github/workflows/daily_build.yaml
--- a/.github/workflows/daily_build.yaml
+++ b/.github/workflows/daily_build.yaml
@@ -56,6 +56,12 @@ jobs:
           echo "CapsuleApp.efi not found for EBBR, raising an error."
           exit 1
         fi
+    - name: Check for UefiDump.efi (EBBR)
+      run: |
+        if [ ! -e "bbr-acs/ebbr/scripts/edk2/Build/MdeModule/DEBUG_GCC5/AARCH64/UefiDump.efi" ]; then
+          echo "UefiDump.efi not found for EBBR, raising an error."
+          exit 1
+        fi
     - name: Get required source codes and tools for SBBR
       run: |
         cd $GITHUB_WORKSPACE  # Go back to the root directory of the repository
