SBBR: add PCIe Option ROM architecture audit
Add a UEFI application to scan PCIe Option ROMs and detect
devices containing UEFI driver images without an AARCH64
UEFI driver, enabling validation of BBR Option ROM
compliance.

Signed-off-by: Sathisha S <sathisha.shivaramappa@arm.com>
Change-Id: I9402fb838db07d3fe3c2e0851cfa0ec7bd94dc16

diff --git a/.github/workflows/daily_build.yaml b/.github/workflows/daily_build.yaml
--- a/.github/workflows/daily_build.yaml
+++ b/.github/workflows/daily_build.yaml
@@ -93,6 +93,12 @@ jobs:
           echo "CapsuleApp.efi not found for SBBR, raising an error."
           exit 1
         fi
+    - name: Check for PcieOptionRomArchAudit.efi (SBBR)
+      run: |
+        if [ ! -e "bbr-acs/sbbr/scripts/edk2/Build/MdeModule/DEBUG_GCC5/AARCH64/PcieOptionRomArchAudit.efi" ]; then
+          echo "PcieOptionRomArchAudit.efi not found for SBBR, raising an error."
+          exit 1
+        fi
     - name: Get required source codes and tools for Standalone FWTS
       run: |
         cd $GITHUB_WORKSPACE  # Go back to the root directory of the repository
